plugin_blacklist:
- safety_area
- image_pub
- vibration
- distance_sensor
- vision_speed
- vision_pose
- px4flow
- mocap
- image
- setpoint_position
- setpoint_attitude
- setpoint_accel
- safety_area
- local_position
- 3dr_radio
- home_position
- vision_speed_estimated
- global_position
- mocap_fake_gps
- rc_io
- mocap_pose_estimate
- manual_control
- setpoint_raw
- setpoint_velocity
- sys_status
- sys_time
- waypoint

plugin_whitelist: []
#- 'sys_*'
